refugie:
    resource: "@RefugieBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

gcamp:
    resource: "@GcampBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# routing.yml / routes.yaml

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
