<?php

namespace GcampBundle\Repository;

/**
 * BesoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinsRepository extends \Doctrine\ORM\EntityRepository
{
}
